# Generated by Django 4.1.4 on 2023-06-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelGuideCategory',
            fields=[
                ('category_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('category_image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TravelGuideRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('image_alt_description', models.CharField(default='Alt Description', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='travelguide',
            name='guide_category',
            field=models.ManyToManyField(related_name='guide_categories', to='guide.travelguidecategory'),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='guide_region',
            field=models.ManyToManyField(related_name='guide_regions', to='guide.travelguideregion'),
        ),
    ]
