# Generated by Django 5.1 on 2024-11-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_travelguidecategory_travelguideregion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelguide',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='travelguide',
            name='guide_category',
        ),
        migrations.RemoveField(
            model_name='travelguide',
            name='guide_region',
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='GuideAuthour',
        ),
        migrations.DeleteModel(
            name='TravelGuideCategory',
        ),
        migrations.DeleteModel(
            name='TravelGuideRegion',
        ),
    ]
