# Generated by Django 5.1 on 2025-02-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_travelguide_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelguide',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
