# Generated by Django 4.1.4 on 2023-03-08 07:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
