# Generated by Django 4.1.4 on 2023-03-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogContent',
        ),
    ]
