# Generated by Django 5.1 on 2025-08-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='banner_image_alt_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
