# Generated by Django 4.1.4 on 2023-02-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_itineraryactivity_highest_altitude_and_more'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_tours', models.ManyToManyField(blank=True, to='activity.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
