# Generated by Django 4.1.4 on 2023-02-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_itineraryactivity_highest_altitude_and_more'),
        ('home', '0002_featuredtour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredtour',
            name='featured_tours',
            field=models.ManyToManyField(blank=True, limit_choices_to={'featured': True}, to='activity.activity'),
        ),
    ]
