# Generated by Django 4.1.4 on 2023-02-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_itineraryactivity_highest_altitude_and_more'),
        ('home', '0003_alter_featuredtour_featured_tours'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredtour',
            name='best_selling_tours',
            field=models.ManyToManyField(blank=True, limit_choices_to={'best_selling': True}, related_name='best_selling_tours', to='activity.activity'),
        ),
        migrations.AddField(
            model_name='featuredtour',
            name='popular_tours',
            field=models.ManyToManyField(blank=True, limit_choices_to={'popular': True}, related_name='popular_tours', to='activity.activity'),
        ),
        migrations.AlterField(
            model_name='featuredtour',
            name='featured_tours',
            field=models.ManyToManyField(blank=True, limit_choices_to={'featured': True}, related_name='featured_tours', to='activity.activity'),
        ),
    ]
