# Generated by Django 4.1.4 on 2023-03-04 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activityenquiry'),
        ('home', '0004_featuredtour_best_selling_tours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=500)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.CharField(blank=True, max_length=500)),
                ('no_of_people', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=500)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity.activity')),
            ],
        ),
    ]
