# Generated by Django 4.1.4 on 2023-03-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_enquiry_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
