# Generated by Django 4.1.4 on 2023-03-08 02:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
