# Generated by Django 4.1.4 on 2023-03-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_teammember_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('order', 'name')},
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
