# Generated by Django 4.1.4 on 2023-03-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_activity_additional_info_activity_altitude_chart_and_more'),
        ('home', '0008_alter_teammember_options_teammember_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredtour',
            name='banner_tour',
            field=models.ManyToManyField(blank=True, related_name='banner_tour', to='activity.activity'),
        ),
        migrations.AddField(
            model_name='featuredtour',
            name='favourite_tours',
            field=models.ManyToManyField(blank=True, related_name='favourite_tours', to='activity.activity'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='source',
            field=models.CharField(choices=[('Trip Advisor', 'Trip Advisor'), ('Trust Pilot', 'Trust Pilot'), ('Google', 'Google'), ('Others', 'Others')], default='Others', max_length=200),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
