# Generated by Django 4.1.4 on 2023-03-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_teammember_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_description',
            field=models.TextField(default='Meta Description Landing Page'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_title',
            field=models.CharField(default='Meta Title Landing Page', max_length=200),
        ),
    ]
