# Generated by Django 4.1.4 on 2023-05-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_siteconfiguration_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(upload_to='')),
                ('image_alt_description', models.CharField(max_length=300)),
            ],
        ),
    ]
