# Generated by Django 4.1.4 on 2023-03-04 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_itineraryactivity_highest_altitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
                ('phone', models.CharField(blank=True, default=' ', max_length=400)),
                ('message', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='activity.activity')),
            ],
        ),
    ]
