# Generated by Django 4.1.4 on 2023-03-08 02:20

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activityenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='tour_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tour_excludes',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tour_highlights',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tour_includes',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.CreateModel(
            name='ActivityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
                ('phone', models.CharField(blank=True, max_length=400)),
                ('message', models.TextField(blank=True)),
                ('no_of_guests', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('booking_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField(blank=True)),
                ('departure_date', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=400)),
                ('emergency_address', models.CharField(blank=True, max_length=400)),
                ('emergency_phone', models.CharField(blank=True, max_length=400)),
                ('emergency_email', models.CharField(blank=True, max_length=400)),
                ('emergency_relationship', models.CharField(blank=True, max_length=400)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='activity.activity')),
            ],
        ),
    ]
