# Generated by Django 4.1.4 on 2023-03-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activity_tour_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ('-order', 'name')},
        ),
        migrations.AddField(
            model_name='destination',
            name='order',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
