# Generated by Django 4.1.4 on 2023-03-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_destination_options_destination_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ('order', 'name')},
        ),
    ]
