# Generated by Django 4.1.4 on 2023-03-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_destination_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
