# Generated by Django 4.1.4 on 2023-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_activity_meta_description_activity_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycategory',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='activityregion',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activityregion',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
