# Generated by Django 4.1.4 on 2023-03-18 11:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_activitycategory_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='additional_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='altitude_chart',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='trek_map',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
