# Generated by Django 4.1.4 on 2023-03-18 11:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_activity_additional_info_activity_altitude_chart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='additional_info',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tour_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tour_excludes',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tour_highlights',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tour_includes',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_detail',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
