# Generated by Django 4.1.4 on 2023-03-19 15:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_alter_activitybooking_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryactivity',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
