# Generated by Django 4.1.4 on 2023-04-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_alter_itineraryactivity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitybooking',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitybooking',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
