# Generated by Django 4.1.4 on 2023-06-26 03:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_activitytestimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityfaq',
            name='answer',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='activityfaq',
            name='question',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
