# Generated by Django 4.1.4 on 2023-07-27 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_alter_activityfaq_answer_alter_activityfaq_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytestimonial',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='activitytestimonial',
            name='role',
        ),
        migrations.RemoveField(
            model_name='activitytestimonial',
            name='source',
        ),
        migrations.CreateModel(
            name='ActivityTestimonialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('activity_testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activity.activitytestimonial')),
            ],
        ),
    ]
