# Generated by Django 4.1.4 on 2023-07-27 07:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_remove_activitytestimonial_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytestimonial',
            name='review',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
