# Generated by Django 4.1.4 on 2024-08-03 11:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_alter_activitytestimonial_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycategory',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='activityregion',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
