# Generated by Django 5.1 on 2024-08-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_activitycategory_content_activityregion_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
