# Generated by Django 5.1 on 2024-08-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_alter_activity_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='availableEnd',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='availableStart',
            field=models.DateField(),
        ),
    ]
