# Generated by Django 5.1 on 2024-09-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0020_alter_activity_availableend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
