# Generated by Django 5.1 on 2024-11-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0022_itineraryactivity_accomodation'),
        ('blog', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='related_activities',
            field=models.ManyToManyField(blank=True, to='activity.activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='related_blogs',
            field=models.ManyToManyField(blank=True, to='blog.post'),
        ),
    ]
