# Generated by Django 5.1 on 2024-11-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0024_cupon_activitybooking_cupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cupon',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
