# Generated by Django 5.1 on 2025-01-05 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0027_activity_meta_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartureDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booked_seats', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_dates', to='activity.activity')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
