# Generated by Django 5.1 on 2025-01-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0028_departuredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitybooking',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activitybooking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activitybooking',
            name='departure_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='departuredate',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
    ]
