# Generated by Django 5.1 on 2025-02-16 05:44

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0031_activity_activity_type_activity_best_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='bag_pack',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
