# Generated by Django 5.1 on 2025-04-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0032_activity_bag_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytestimonial',
            name='source',
            field=models.CharField(blank=True, choices=[('Trip Advisor', 'Trip Advisor'), ('Trust Pilot', 'Trust Pilot'), ('Google', 'Google'), ('Tour Radar', 'Tour Radar'), ('YetiHikes', 'YetiHikes'), ('Get Your Guide', 'Get Your Guide'), ('Others', 'Others')], default='Others', max_length=500),
        ),
    ]
