# Generated by Django 5.1 on 2025-08-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0033_alter_activitytestimonial_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='avatar_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='banner_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
